<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>SAMERIDER</AssemblyName>
    <Version>1.06</Version>
    <InformationalVersion>1.06</InformationalVersion>
    <ApplicationIcon>../../SAMERIDER.ico</ApplicationIcon>
    <RuntimeIdentifiers>win-x64;osx-arm64;osx-x64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../SAMERIDER.ico" LogicalName="SAMERIDER.App.SAMERIDER.ico" />
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.119.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SAMERIDER.Core\SAMERIDER.Core.csproj" />
    <ProjectReference Include="..\SAMERIDER.Editor\SAMERIDER.Editor.csproj" />
  </ItemGroup>
</Project>
